### ISSUE TITLE
git:// versus https:// in install-additional-software.sh

### ISSUE THREAD

**Issue by daveuu** [cbg-ethz/haploclique#24]
`install-additional-software.sh` hangs on cloning via git:// URLs but using https:// URLs instead works. Maybe because I'm behind a firewall proxy or maybe because of a change at github.com?

This is a fix:
```
sed -i -e "s/git:/https:/g" install-additional-software.sh
```

**Comment by armintoepfer** [comment]
Thanks for the notice, very soon, we'll release the latest version that automatizes the global reconstruction. No external tools needed anymore :) Have a look at the development branch
