### ISSUE TITLE
install mac

### ISSUE THREAD

**Issue by antoine4ucsd** [cbg-ethz/haploclique#34]
Hi,
I am very interested in your software to use on MiSeq HIV data
I've just installed haploclique on my Mac with the followings:
git clone https://github.com/cbg-ethz/haploclique && cd haploclique
git submodule update --init --remote
mkdir build && cd build
cmake .. && make
No errors.
Haploclique should now be installed in the following dir:
/Users/myname/Documents/haploclique/

When I tried to test it on bam file with the following command but I get this error:

<img width="807" alt="screen shot 2017-03-15 at 10 07 12 am" src="https://cloud.githubusercontent.com/assets/18502631/23961134/39127658-0967-11e7-9ea0-13f7143eb66b.png">

It is probably something obvious...Any chance you can help me?
Let me know if you need any other info.
thanks!
a

**Comment by armintoepfer** [comment]
- Why are calling haploclique-assembly, this call is deprecated? Could you please point me to the particular docu?
 - After `make`, the binary won't be moved anywhere. With `make install` it will be moved to your binary directory or the directory of your choice. How to select the install directory is described in our install docs.

**Comment by antoine4ucsd** [comment]
thanks Armin!
Just realized that haploclique-assembly was deprecated. I tried the following command on some sample test and I got the following:

<img width="806" alt="screen shot 2017-03-15 at 10 39 59 am" src="https://cloud.githubusercontent.com/assets/18502631/23962563/c77d125a-096b-11e7-965b-8d4aec0e14c4.png">

I will keep working on it but if you see any obvious mistake, all advices are warmly welcome!
thanks again,

**Comment by armintoepfer** [comment]
Looks like the libbamtools library is not in your LD_LIBRARY_PATH. It should be have been compiled along the binary. If you find it, add the absolute path like
```
export DYLD_LIBRARY_PATH=/your/path/to/the/lib/dir:$DYLD_LIBRARY_PATH
```

Let us know how it went

**Comment by antoine4ucsd** [comment]
Yeah!
For some reason, I had to export the libbamtools library as you suggested even if it was installed in my path:
usr/local/lib/bamtools
Anyway, I am running a first test on interleaved paired end MiSeq HIV reads already cleaned and filtered with our local pipeline.  I would be very interested in sharing with you our first results. I will play around all the option.
It doesn't look like the -r (for reference) is in the arg list anymore though? 

thanks again for being so responsive!
a

**Comment by armintoepfer** [comment]
My pleasure. The internals have been enhanced, thus the re-alignment step and the necessity of a reference has been obsoleted.

**Comment by antoine4ucsd** [comment]
thanks!
We are currently using both PacBio and MiSeq platform in the lab.
For the latter (reads ~250-350bp), I was willing to map and reassemble long amplicons from filtered cleaned reads encompassing a given region based on primers from the attached paper.
Do you think this is unrealistic?

The basic command I just used generated hundreds of short ‘clique’ variants.
haploclique F1map.bam F1.out

the data input are my interleaved reads after clean up and filtering using the following pipeline:
https://github.com/iosonofabio/hivwholeseq <https://github.com/iosonofabio/hivwholeseq>

If you are interested and if you have time(…), I would be happy to have your thoughts about it

thanks,
a

**Comment by tobiasmarschall** [comment]
@armintoepfer @MaryamZaheri  We should provide a bioconda recipe to easy installation. I will create an issue for this.

@antoine4ucsd We will have a tutorial on virus sequencing that will also cover haploclique at [BC2](https://www.bc2.ch/2017/) on Sept 12. Maybe that'd be a good opportunity to get in touch in person. (In the meantime, we are of course happy to discuss online.)

**Comment by antoine4ucsd** [comment]
Thank you both!
@tobiasmarschall , I'd love to assist this conference but not sure if I'll be able to make it. 
While my install seems to have worked properly, I am struggling with the first generated variants. I guess smthg went wrong. We can share a set of data if you have time to take a quick look. I was able to generate realistic allele freq and a pretty good coverage with my own pipeline and the consensi are fine (generated with my pipeline or with IVA). 
My goal would be to reconstruct some 'representative' haplotypes from these long amplicons. Any advices? Specific options on haplocliques?
The bam file I used as input for haploclique is the cleaned filtered interleaved reads obtained with my pipeline. 
We can close this post and discussed about it online.
Thanks again!

**Comment by tobiasmarschall** [comment]
@MaryamZaheri Would you have time to look at such a data set? I think it would be valuable to figure out what might have gone wrong.

**Comment by MaryamZaheri** [comment]
Hi all,

I would be more than happy help. @antoine4ucsd If it is possible please share your data so I can take a look. How large is you data file?

**Comment by antoine4ucsd** [comment]
I can send you a subset of reads. How should we proceed?

thanks!

**Comment by MaryamZaheri** [comment]
If it is less than 10Mb send it by email to maryam.zaheri@bsse.ethz.ch. Otherwise share it with google drive, my account is zaheri@gmail.com.
