### ISSUE TITLE
How set the number of threads?

### ISSUE THREAD

**Issue by seoanezonjic** [cbg-ethz/haploclique#40]
I'm using the last release of hapliclique and I had seen that use pthreads. How can I set more than one thread to do the analysis?
Thanks
Pedro

**Comment by collurio229** [comment]
The old version of Haploclique did parallelization by simply partitioning the reads in several datasets, and then running haploclique with GNU parallel on every dataset. This meant that edges between reads in different partitions were not considered for the first iteration of clique enumeration, leading to some loss of information.
After rewriting the original bash script handling the iterations directly into the C++ code, the parallelization part of the script didn't make it into the new version.

**Comment by armintoepfer** [comment]
The remark about losing information in the old version is wrong.

Too bad that parallelization didn't make it.
