### ISSUE TITLE
Two short questions about haploclique capabilities ? 

### ISSUE THREAD

**Issue by jblamyatifremer** [cbg-ethz/haploclique#43]
Dear Haploclique Creators, 

1- Could we use Haploclique on DNA virus dataset ?
2- Does Haploclique could manage large insertion elements (>1000 bp) ? It could be problematic since the read length is samller compare to deletion length indeed this information is not contain in Bam file (I see the help page that structural variant is not fully supported).

Cheers, 

JB

**Comment by MaryamZaheri** [comment]
Hi,

1- Sure, you can use it on DNA virus datasets. 
2- Haploclique can handle large structural variation. However, we are improving the performance of the basic algorithm and later this will be re-activated.
