### ISSUE TITLE
Empty output files

### ISSUE THREAD

**Issue by ruby-r** [cbg-ethz/haploclique#47]
Hello. when I run haploclique-assembly, i get the output files (the latter 7 of which are 0 bytes):

consensus.fasta
statistics.txt
deletions.txt
alignment.prior
data_clique_to_reads.tsv
data_cliques_paired_R1.fastq
data_cliques_paired_R2.fastq
data_cliques_single.fastq
quasispecies.fasta
singles.prior

and the following error:

[E::hts_open_format] fail to open file 'single_sort.bam'
samtools view: failed to open "single_sort.bam" for reading: No such file or directory
rm: single_sort.bam: No such file or directory
mv: rename x*-dir to x*-dir/alignment.prior: Invalid argument
cat: alignment.prior: No such file or directory
STATUS
Cliques/Uniques/CPU time:	0/0/0
Error correction of singletons
cat: x*/data_cliques_paired_R1.fastq: No such file or directory
cat: x*/data_cliques_paired_R2.fastq: No such file or directory
cat: x*/data_cliques_single.fastq: No such file or directory
cat: x*/data_clique_to_reads.tsv: No such file or directory
Max read length:		0 bp
mv: rename x*-dir to x*-dir/alignment.prior: Invalid argument
cat: alignment.prior: No such file or directory
STATUS
Cliques/Uniques/CPU time:	0/0/0
cat: x*/data_cliques_paired_R1.fastq: No such file or directory
cat: x*/data_cliques_paired_R2.fastq: No such file or directory
cat: x*/data_cliques_single.fastq: No such file or directory
cat: x*/data_clique_to_reads.tsv: No such file or directory
Max read length:		0 bp

I have all of the dependencies installed (and updated). I would greatly appreciate any advice as to what this error message means and how to rectify it. thank you!

**Comment by MaryamZaheri** [comment]
Hi, Why don't you use the current version of Haploclique (the current master branch)?
