### ISSUE TITLE
Error: Unable to access jarfile /ConsensusFixer.jar

### ISSUE THREAD

**Issue by zusman** [cbg-ethz/haploclique#53]
The haploclique-assembly can not find ConsensusFixer jar file and there is no detail on where to put this jar file. Can you please let me know how to resolve it? I have already tried placing the said .jar file in bin build and external folders.

$ haploclique-assembly -r hbv_refseq.fasta -i C7_mapped.bam 
Error: Unable to access jarfile /ConsensusFixer.jar
[E::hts_open_format] fail to open file 'single_sort.bam'
samtools view: failed to open "single_sort.bam" for reading: No such file or directory
rm: cannot remove ‘single_sort.bam’: No such file or directory
STATUS: 169
Cliques/Uniques/CPU time:	62/41/1
STATUS: 200
Cliques/Uniques/CPU time:	100/52/1
Error correction of singletons
Max read length:		378 bp
STATUS: 47
Cliques/Uniques/CPU time:	0/0/0
cat: x*/data_cliques_paired_R1.fastq: No such file or directory
cat: x*/data_cliques_paired_R2.fastq: No such file or directory
cat: x*/data_cliques_single.fastq: No such file or directory
cat: x*/data_clique_to_reads.tsv: No such file or directory
Max read length:		378 bp
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
mv: cannot stat ‘single_2.bam’: No such file or directory

**Comment by armintoepfer** [comment]
The latest `master` version does not even use ConsensusFixer. Please use the latest HEAD
