### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by DrYak** [cbg-ethz/haploclique#54]
Hi @armintoepfer !

Would you (or anybody else with the necessary access rights enabled) mind tagging a v1.0.2 release of [the latest commits currently in master](https://github.com/cbg-ethz/haploclique/compare/1.0.1...7823b24585bc73b494a14341604027d9808224b8) so I can try to make a [bioconda recipe](https://github.com/cbg-ethz/haploclique/issues/35) out of them ?

Thanks a lot in advance !

**Comment by DrYak** [comment]
Also, it would be great if you could include a [LICENSE](https://www.gnu.org/licenses/gpl-3.0.en.html) file together with that release, like @SoapZA [did for small genome utilities](https://github.com/cbg-ethz/smallgenomeutilities/commit/72917e7beed8b00460d6f7b9e6edf1de5021c69a).

**Comment by DrYak** [comment]
By the way, I've found the following fix seems to be needed on older versions of GCC :
```shell
sed -i '/#define .*_H_/a#include <memory>' src/{AlignmentRecord,HistogramBasedDistribution}.
```
Without this, the definition of `std::unique_ptr` is missing in a few places.
I'll make a pull request shortly.

Also, a bioconda specific-fix:
```shell
sed -ri 's@#include <regex>@#include <boost/regex.hpp>@;s/std::(s?regex|smatch)/boost::\1/g' src/docopt/docopt.cpp
```
bioconda ships only with version 4.8.x of GCC (probably because of CentOS 7).
But as reported by dpcopt's [readme](https://github.com/cbg-ethz/haploclique/blob/master/src/docopt/README.rst), GCC 4.8.x's regex is broken, and only fixed in 4.9.0
so the build script I'm writing will force a switch to Boost's regex (which is a super-set of C++11's regex) in this specific situation.

It has nothing to do with Haploclique. Hapoclique is working correctly as it should, so there is no reason to modify it.

**Comment by DrYak** [comment]
Here's the [pull request](https://github.com/cbg-ethz/haploclique/pull/55) I need before 1.0.2 is tagged, in order to be able to make a bioconda recipe.

**Comment by DrYak** [comment]
i'm still not ready with my C++11 -> Boost "regex engine swap" :
I'm getting exceptions thrown from within docopt due to (char *)NULL to std::string conversions.

I'll investigate further next week.

(so no tagging for now...)

**Comment by armintoepfer** [comment]
I inc'd to v1.3.0 and tagged.

**Comment by DrYak** [comment]
Thanks.
I'll try to find fixes around the thrown exceptions (maybe a few more fixes pulling will be needed)
And we should be set and ready for bioconda.

**Comment by DrYak** [comment]
Yet [another pull request](https://github.com/cbg-ethz/haploclique/pull/57) necessary before a successful bioconda recipe. It has two changes :

- first is upgrading docopt which fixes bugs (and simplifies using the old regex-less GCC 4.8 still used by bioconda).
- second is changing behavious of `-h` as required by bioconda recipes' tests.

**Comment by DrYak** [comment]
Bioconda recipe is fully functional after that (at least it passes the unit tests)
